FROM apotris-arm64-glibc231

ENV PATH="/root/.cargo/bin:$PATH"

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable --profile minimal \
 && rustup target add aarch64-unknown-linux-gnu
